language: rust
sudo: required
dist: trusty
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --no-default-features
  - cargo test --no-run --verbose --no-default-features
  - cargo build --verbose --features "use-socketcan"
  - cargo test --verbose --features "use-socketcan"

addons:
  apt:
    packages:
      - libssl-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin -v --all-features --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
